CREATE TABLE `Students` (
  `studId` int(5) NOT NULL AUTO_INCREMENT,
  `appliedDate` date DEFAULT NULL,
  `firstName` varchar(100) DEFAULT NULL,
  `middleName` varchar(100) DEFAULT NULL,
  `lastName` varchar(100) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `uid` varchar(15) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `contact` varchar(20) DEFAULT NULL,
  `parentContact` varchar(20) DEFAULT NULL,
  `photo` varchar(200) DEFAULT NULL,
  `sign` varchar(200) DEFAULT NULL,
  `currentAddress` varchar(1000) DEFAULT NULL,
  `permanentAddress` varchar(1000) DEFAULT NULL,
  `guardianName` varchar(300) DEFAULT NULL,
  `guardianOccupation` varchar(50) DEFAULT NULL,
  `guardianAddress` varchar(1000) DEFAULT NULL,
  `guardianEmail` varchar(100) DEFAULT NULL,
  `guardianContact` varchar(20) DEFAULT NULL,
  `deptName` varchar(50) DEFAULT NULL,
  `qualification` varchar(50) DEFAULT NULL,
  `courseName` varchar(100) DEFAULT NULL,
  `courseDuration` varchar(5) DEFAULT NULL,
  `courseYear` varchar(5) DEFAULT NULL,
  `eligibilityNo` varchar(20) DEFAULT NULL,
  `admissionDate` date DEFAULT NULL,
  `admissionYear` varchar(5) DEFAULT NULL,
  `isRoomAllotted` varchar(5) DEFAULT NULL,
  `hostelNo` varchar(5) DEFAULT NULL,
  `roomNo` varchar(5) DEFAULT NULL,
  `approvalStatus` varchar(5) DEFAULT 'W',
  `deleteStatus` varchar(5) DEFAULT 'N',
  PRIMARY KEY (`studId`)
)
